- name: Configure Linux System
  hosts: linux
  become: true
  gather_facts: true
  tasks:
    - name: Install tools
      ansible.builtin.yum:
        name:
          - bash-completion
          - htop
          - vim
          - yum-utils
        state: latest

    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled
      ignore_errors: true
      register: selinux_result

    - name: Change SELinux in /etc/selinux/config to disabled
      ansible.builtin.lineinfile:
        path: /etc/selinux/config
        regex: 'SELINUX=enforcing'
        line: 'SELINUX=disabled'
      when: selinux_result is failed

    - name: Create a directory /var/log/journal
      ansible.builtin.file:
        path: /var/log/journal
        state: directory
        mode: '0755'

    - name: Restart Journalctl
      ansible.builtin.systemd_service:
        name: systemd-journald
        state: restarted
        enabled: true

    - name: Update yum
      ansible.builtin.yum:
        name: '*'
        state: latest

    - name: Reboot the machine (Wait for 5 min)
      ansible.builtin.reboot:
        reboot_timeout: 300
