---
- name: Install and configure Elasticsearch on all nodes
  hosts: es
  become: yes
  vars:
    es_version: "7.17.23"

  tasks:
    - name: Install Java
      dnf:
        name: java-21-openjdk
        state: present

    - name: Download Elasticsearch RPM
      get_url:
        url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ es_version }}-x86_64.rpm"
        dest: /tmp/elasticsearch-{{ es_version }}.rpm

    - name: Install Elasticsearch
      dnf:
        name: /tmp/elasticsearch-{{ es_version }}.rpm
        state: present
        disable_gpg_check: true

    - name: Configure Elasticsearch
      template:
        src: elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
        owner: root
        group: elasticsearch
        mode: '0644'

    - name: Ensure /data/backup_es directory exists
      ansible.builtin.file:
        path: /data/backup_es
        state: directory
        owner: elasticsearch
        group: elasticsearch
        mode: '0755'

    - name: Ensure Elasticsearch is started and enabled
      service:
        name: elasticsearch
        state: restarted
        enabled: yes
